"""Blockchain chain identifiers."""

# Ethereum
ETHEREUM_MAINNET_CHAIN_ID = 1
ETHEREUM_GOERLI_CHAIN_ID = 5
ETHEREUM_SEPOLIA_CHAIN_ID = 11155111

# Layer 2s
ARBITRUM_ONE_CHAIN_ID = 42161
OPTIMISM_CHAIN_ID = 10
BASE_CHAIN_ID = 8453
POLYGON_CHAIN_ID = 137
